export const PROJECTS_SELECTOR_KEY = 'projects-selector'
export const PROJECT_KEY = 'project'
export const GROUPS_KEY = 'groups'
export const GROUPS_NAV_KEY = 'groups-nav'
export const URLS_KEY = 'urls'
