name: envger-environment

services:
  postgres:
    container_name: envger-db
    image: postgres:16.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: envger
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
