name: guard-notes-environment

services:
  postgres:
    container_name: guard-notes-database
    image: postgres:16.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: guard-notes
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
