name: Envger CI

on:
  # Evento para cuando se crea o actualiza un Pull Request
  pull_request:
    branches:
      - develop
      - main

  # Evento para cuando un Pull Request es cerrado (posible merge)
  pull_request_target:
    types:
      - closed
    branches:
      - develop
      - main

permissions:
  contents: write

jobs:

  checkout-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.1

  # Job para verificar la construcción de la imagen en Pull Requests
  check-build-image:
    # Se ejecuta cuando el evento es 'pull_request' (creación o actualización de un PR)
    if: ${{ github.event_name == 'pull_request' }}
    needs: checkout-code
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 'latest'
          cache: true  # Habilita la caché de pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build the project
        run: pnpm run build
        
  # Job para ejecutar semantic-release cuando el PR es mergeado
  semantic-release:
    # Se ejecuta cuando el evento es 'pull_request_target' y el PR fue mergeado
    if: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.merged == true }}
    needs: checkout-code
    runs-on: ubuntu-latest

    steps:
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Do something when a new release published
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo ${{ steps.semantic.outputs.new_release_version }}
          echo ${{ steps.semantic.outputs.new_release_major_version }}
          echo ${{ steps.semantic.outputs.new_release_minor_version }}
          echo ${{ steps.semantic.outputs.new_release_patch_version }}
